### ISSUE TITLE
debian, ppa

### ISSUE THREAD

**Issue by nschloe** [metux/vtk8#1]
Just FYI, I'm working on VTK8 in Debian and it's looking good. Check out [the Debian repo](https://salsa.debian.org/science-team/vtk8); there's also [a PPA](https://launchpad.net/~nschloe/+archive/ubuntu/vtk8).

**Comment by metux** [comment]
Oh, great :)
I've been inactive on that front for quite a while, so it's great that somebody else steps in :)

By the way: any special reason for still using the old text-based patches ?
I really wonder why anybody still likes to go that complicated way :p 
Few days ago, we had a discussion about that on debian-devel - maybe you'd like to have a look at it.

--mtx

**Comment by nschloe** [comment]
> By the way: any special reason for still using the old text-based patches ?

It's just what came from the vtk7 packaging. I'll be happy to look at more modern alternatives. Link?

**Comment by metux** [comment]
Here's the discussion we recently had @debian-devel:
http://lists-archives.com/debian-devel/235510-survey-git-packaging-practices-repository-format.html

In short words:
* branch off generic maintenance branch from the corresponding upstream release tag and add generic (potentially upstreamable) patches there, finally tag it
* branch off the debianization branch the mnt branch and add deb specific patches here, finally tag it.
* when updating to new upstream version, rebase onto it, retaining the branch hierarchy - when existing patches need fixing, amend it
* in general: try to keep the history clean and easy to understand
* try to do as much as possible in generic way: eg. when things like pathes need to be customized pof features switched off, introduce generic build flags

One of the goals here is trying to make most of the work reusable for upstreams or other distros.

--mtx

**Comment by nschloe** [comment]
Yeah, sounds really complicated. :) I'll stick with `debian/patches` for now, trying to get them upstream.
